{% set version = "3.7.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: f9db84ed398df5109bd69c11d46613d16cc572fb9ad3213f10d95e2b5f12c18e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    # optional [all]
    - markuppy
    - odfpy
    - openpyxl >=2.6.0
    - pandas
    - pyyaml
    - tabulate
    - xlrd
    - xlwt

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - tablib
    - tablib.formats
  source_files:
    - tests/test_tablib.py
  commands:
    - python tests/test_tablib.py
    - pip check

about:
  home: https://pypi.org/project/tablib/
  summary: Format agnostic tabular data library (XLS, JSON, YAML, CSV)
  dev_url: https://github.com/jazzband/tablib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
