{% set version = "3.5.0" %}

package:
  name: tablib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tablib/tablib-{{ version }}.tar.gz
  sha256: f6661dfc45e1d4f51fa8a6239f9c8349380859a5bfaa73280645f046d6c96e33

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=58
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    # optional [all]
    - markuppy
    - odfpy
    - openpyxl >=2.6.0
    - pandas
    - pyyaml
    - tabulate
    - xlrd
    - xlwt

test:
  requires:
    - pip
    - pytest
  imports:
    - tablib
    - tablib.formats
    - tablib.packages
  source_files:
    - tests/test_tablib.py
  commands:
    - python tests/test_tablib.py
    - pip check

about:
  home: https://pypi.org/project/tablib/
  summary: Format agnostic tabular data library (XLS, JSON, YAML, CSV)
  dev_url: https://github.com/jazzband/tablib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
